-- ============================================================
-- Generic notification outbox for transactional emails
-- ============================================================

begin;

create table if not exists public.notification_events (
  id uuid not null default gen_random_uuid(),
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  event_type text not null,
  aggregate_type text not null,
  aggregate_id uuid not null,
  aggregate_version timestamp with time zone null,
  guest_id uuid null,
  dedupe_key text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  attempts integer not null default 0,
  next_attempt_at timestamp with time zone not null default timezone('utc'::text, now()),
  claimed_at timestamp with time zone null,
  processed_at timestamp with time zone null,
  failed_at timestamp with time zone null,
  last_error text null,

  constraint notification_events_pkey primary key (id),
  constraint notification_events_guest_id_fkey
    foreign key (guest_id)
    references public.guests(id)
    on delete set null,
  constraint notification_events_dedupe_key_key unique (dedupe_key),
  constraint notification_events_status_check
    check (status in ('pending', 'processing', 'processed', 'failed'))
);

create table if not exists public.notification_deliveries (
  id uuid not null default gen_random_uuid(),
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  event_id uuid not null,
  recipient_type text not null,
  recipient_email text null,
  channel text not null default 'email',
  dedupe_key text not null,
  status text not null default 'pending',
  attempts integer not null default 0,
  claimed_at timestamp with time zone null,
  sent_at timestamp with time zone null,
  failed_at timestamp with time zone null,
  skipped_at timestamp with time zone null,
  last_error text null,

  constraint notification_deliveries_pkey primary key (id),
  constraint notification_deliveries_event_id_fkey
    foreign key (event_id)
    references public.notification_events(id)
    on delete cascade,
  constraint notification_deliveries_dedupe_key_key unique (dedupe_key),
  constraint notification_deliveries_recipient_type_check
    check (recipient_type in ('admin', 'guest')),
  constraint notification_deliveries_channel_check
    check (channel in ('email')),
  constraint notification_deliveries_status_check
    check (status in ('pending', 'processing', 'sent', 'failed', 'skipped'))
);

create index if not exists notification_events_pending_idx
  on public.notification_events (status, next_attempt_at, created_at)
  where status = 'pending';

create index if not exists notification_events_guest_pending_idx
  on public.notification_events (guest_id, status, next_attempt_at, created_at)
  where status = 'pending';

create index if not exists notification_deliveries_event_id_idx
  on public.notification_deliveries (event_id);

alter table public.notification_events enable row level security;
alter table public.notification_deliveries enable row level security;

revoke all on table public.notification_events from anon, authenticated;
revoke all on table public.notification_deliveries from anon, authenticated;

grant select, insert, update, delete
  on table public.notification_events
  to service_role;

grant select, insert, update, delete
  on table public.notification_deliveries
  to service_role;

comment on table public.notification_events is
  'Outbox of transactional notification events generated by trusted database operations.';

comment on table public.notification_deliveries is
  'Per-recipient delivery log for transactional notifications.';

commit;
